<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ERP.Core.Database.Domain" Version="1.115.1" />
    <PackageReference Include="ERP.Core.Domain" Version="1.115.1" />
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1873</NoWarn>
    <RootNamespace>ERP.Core.Warehouse.Api.Domain</RootNamespace>
  </PropertyGroup>

</Project>
